"""Image upload and retrieval.

Images arrive from the client as base64 data URLs (so the Flutter client can
use the same code path on web and native without multipart form differences).
They are validated with Pillow, written to the configured directory, and
referenced from messages by a server-generated filename only — never by a
client-supplied name — so there is no path-traversal surface.

The provider adapters read images back through :func:`read_image_base64` when
they need to forward an image upstream.
"""

from __future__ import annotations

import base64
import binascii
import os
import re
import uuid
from io import BytesIO
from typing import Any

import anyio
from PIL import Image

from .config import Settings

_DATA_URL_RE = re.compile(
    r"data:image/(?P<ext>[a-zA-Z0-9.+]+);base64,(?P<data>.+)",
    re.DOTALL,
)
"""Pattern for ``data:image/<ext>;base64,<data>`` URLs."""

_ALLOWED_EXTS: dict[str, str] = {
    "png": "png",
    "jpeg": "jpg",
    "jpg": "jpg",
    "webp": "webp",
    "gif": "gif",
}
"""Allowed source formats mapped to the on-disk extension used for storage."""

_MEDIA_TYPES: dict[str, str] = {
    "png": "image/png",
    "jpg": "image/jpeg",
    "webp": "image/webp",
    "gif": "image/gif",
}


class ImageError(ValueError):
    """Raised when an image cannot be parsed or fails validation."""


def _parse_and_validate(data_url: str, max_bytes: int) -> tuple[str, bytes]:
    """Decode a data URL and return ``(extension, raw_bytes)``.

    Validation has two layers: the base64 must parse, and Pillow must be able
    to open and verify the image as a real picture in an allowed format. The
    byte-length check happens before Pillow so an oversized upload is
    rejected without the CPU cost of decoding it.
    """
    match = _DATA_URL_RE.match(data_url)
    if not match:
        raise ImageError("not a valid image data URL")
    ext = match.group("ext").lower()
    if ext not in _ALLOWED_EXTS:
        raise ImageError(f"unsupported image format: {ext}")
    try:
        data = base64.b64decode(match.group("data"))
    except (binascii.Error, ValueError) as exc:
        raise ImageError("invalid base64 image data") from exc
    if len(data) > max_bytes:
        raise ImageError("image exceeds the maximum allowed size")
    try:
        image = Image.open(BytesIO(data))
        image.verify()
    except Exception as exc:  # Pillow raises a variety of types on corrupt input
        raise ImageError("corrupt or unreadable image") from exc
    return _ALLOWED_EXTS[ext], data


def _write_image_sync(upload_dir: str, ext: str, data: bytes) -> str:
    """Synchronous helper that creates the directory and writes the file.

    Intended to run in a worker thread via :func:`anyio.to_thread.run_sync`
    so the event loop is not blocked while doing disk I/O.
    """
    os.makedirs(upload_dir, exist_ok=True)
    filename = f"{uuid.uuid4().hex}.{ext}"
    path = os.path.join(upload_dir, filename)
    with open(path, "wb") as handle:
        handle.write(data)
    return filename


async def save_image(data_url: str, settings: Settings) -> str:
    """Validate and persist an image, returning the generated filename.

    The filename (not the full path) is returned so callers can store it in
    the database and construct a URL with the API base prefix.
    """
    ext, data = await anyio.to_thread.run_sync(
        _parse_and_validate, data_url, settings.app_config.images.max_bytes
    )
    return await anyio.to_thread.run_sync(
        _write_image_sync, settings.app_config.images.upload_dir, ext, data
    )


def _read_image_sync(upload_dir: str, filename: str) -> tuple[str, bytes]:
    """Read an image from disk and return ``(extension, raw_bytes)``."""
    path = os.path.join(upload_dir, filename)
    ext = filename.rsplit(".", 1)[-1].lower()
    with open(path, "rb") as handle:
        return ext, handle.read()


async def read_image_base64(
    settings: Settings,
    filename: str,
) -> tuple[str, str]:
    """Return ``(media_type, base64_data)`` for an image stored on disk.

    Used by provider adapters when forwarding an image upstream. The media
    type is derived from the file extension and is safe because filenames
    are generated by the server.
    """
    ext, data = await anyio.to_thread.run_sync(
        _read_image_sync, settings.app_config.images.upload_dir, filename
    )
    if ext not in _MEDIA_TYPES:
        raise ImageError(f"unknown stored image extension: {ext}")
    return _MEDIA_TYPES[ext], base64.b64encode(data).decode("ascii")


def image_url_for(filename: str | None) -> str | None:
    """Build the client-facing URL for a stored image filename."""
    if not filename:
        return None
    return f"/images/{filename}"


def safe_filename(filename: str) -> Any:
    """Reject filenames that contain path separators.

    The static-file mount already prevents traversal, but this guard keeps
    any direct lookups safe and makes the intent explicit at the call site.
    """
    if not filename or "/" in filename or "\\" in filename or ".." in filename:
        raise ImageError("invalid image filename")
    return filename
